import connect from "../connect/connect.js";
import Product from '../models/product_schema.js';

connect();
// title: {type : String, required : true},
// description : {type : String, required : true},
// price: {type : Number, required : true},
// star : {type : String, required : true},
// review : {type : Number, required : true},
// discount : {type: Number, required : true},
// tag : {type : String, required : true},
// categories : {type : String, required : true},
// image : {type : String}

await Product.create(
// { title: "아보카도", description: "유기농 아보카도 3개입", price: 8700, star: "4.9", review: 678, discount: 25, tag: "NEW", categories: "채소" },
//   { title: "바나나", description: "신선한 바나나 5개입", price: 4500, star: "4.8", review: 1205, discount: 15, tag: "NEW", categories: "과일" },
//   { title: "키위", description: "달콤한 키위 6개입", price: 5500, star: "4.7", review: 987, discount: 10, tag: "NEW", categories: "과일" },
//   { title: "사과", description: "유기농 사과 6개입", price: 6800, star: "4.9", review: 1543, discount: 20, tag: "SALE", categories: "과일" },
//   { title: "배", description: "신선한 배 4개입", price: 7800, star: "4.6", review: 465, discount: 12, tag: "NEW", categories: "과일" },
//   { title: "토마토", description: "신선한 토마토 500g", price: 3200, star: "4.8", review: 234, discount: 5, tag: "NEW", categories: "채소" },
//   { title: "당근", description: "신선한 당근 1kg", price: 3900, star: "4.7", review: 212, discount: 8, tag: "NEW", categories: "채소" },
//   { title: "시금치", description: "유기농 시금치 300g", price: 3200, star: "4.8", review: 421, discount: 10, tag: "NEW", categories: "채소" },
//   { title: "오이", description: "신선한 오이 3개입", price: 2500, star: "4.5", review: 532, discount: 15, tag: "NEW", categories: "채소" },
//   { title: "파프리카", description: "파프리카 3개입", price: 3800, star: "4.6", review: 312, discount: 10, tag: "NEW", categories: "채소" },
//   { title: "레몬", description: "신선한 레몬 4개입", price: 4800, star: "4.7", review: 654, discount: 5, tag: "NEW", categories: "과일" },
//   { title: "귤", description: "달콤한 귤 10개입", price: 6200, star: "4.8", review: 908, discount: 18, tag: "NEW", categories: "과일" },
//   { title: "망고", description: "신선한 망고 2개입", price: 9500, star: "4.9", review: 345, discount: 20, tag: "NEW", categories: "과일" },
//   { title: "포도", description: "신선한 포도 500g", price: 5300, star: "4.7", review: 765, discount: 12, tag: "NEW", categories: "과일" },
//   { title: "딸기", description: "신선한 딸기 300g", price: 7500, star: "4.9", review: 980, discount: 5, tag: "NEW", categories: "과일" },
//   { title: "오렌지", description: "신선한 오렌지 6개입", price: 5900, star: "4.8", review: 400, discount: 8, tag: "NEW", categories: "과일" },
//   { title: "청포도", description: "청포도 500g", price: 6800, star: "4.8", review: 342, discount: 15, tag: "NEW", categories: "과일" },
//   { title: "감자", description: "유기농 감자 1kg", price: 2800, star: "4.5", review: 212, discount: 10, tag: "SALE", categories: "채소" },
//   { title: "양배추", description: "신선한 양배추 1kg", price: 3300, star: "4.6", review: 120, discount: 5, tag: "NEW", categories: "채소" },
//   { title: "배추", description: "신선한 배추 1개", price: 4500, star: "4.7", review: 678, discount: 12, tag: "NEW", categories: "채소" }
{ title: "비건 닭가슴살", description: "식물성 단백질로 만든 비건 닭가슴살 500g", price: 9800, star: "4.9", review: 350, discount: 15, tag: "NEW", categories: "고기대용" },
{ title: "두부 스테이크", description: "두부로 만든 고기 대체 스테이크 4개입", price: 6200, star: "4.8", review: 240, discount: 10, tag: "NEW", categories: "고기대용" },
{ title: "렌틸콩 버거", description: "고단백 렌틸콩으로 만든 버거 패티 6개입", price: 7500, star: "4.7", review: 512, discount: 5, tag: "NEW", categories: "고기대용" },
{ title: "불고기 맛 양배추", description: "불고기 양념을 입힌 양배추 500g", price: 3200, star: "4.6", review: 312, discount: 8, tag: "NEW", categories: "채식반찬" },
{ title: "고구마 조림", description: "달콤한 고구마 조림 300g", price: 2800, star: "4.9", review: 450, discount: 12, tag: "NEW", categories: "채식반찬" },
{ title: "시금치 된장국", description: "신선한 시금치와 된장으로 만든 전통적인 된장국", price: 3300, star: "4.8", review: 580, discount: 10, tag: "NEW", categories: "채식반찬" },
{ title: "고추장 멸치볶음", description: "매콤한 고추장 양념 멸치볶음 200g", price: 4500, star: "4.7", review: 312, discount: 15, tag: "NEW", categories: "채식반찬" },
{ title: "김치전", description: "바삭하게 구운 김치전 5개입", price: 5200, star: "4.9", review: 756, discount: 8, tag: "NEW", categories: "채식반찬" },
{ title: "쌀국수", description: "향긋한 고수와 함께 즐기는 쌀국수", price: 6800, star: "4.8", review: 430, discount: 10, tag: "NEW", categories: "간편식" },
{ title: "라면", description: "매운 라면 5개입", price: 3500, star: "4.7", review: 890, discount: 15, tag: "NEW", categories: "간편식" },
{ title: "간편 볶음밥", description: "30초 만에 완성되는 간편 볶음밥", price: 2900, star: "4.6", review: 660, discount: 10, tag: "NEW", categories: "간편식" },
{ title: "치킨너겟", description: "바삭하고 고소한 치킨너겟 10개입", price: 6500, star: "4.9", review: 320, discount: 20, tag: "NEW", categories: "간식과일견과" },
{ title: "허니머스타드 너겟", description: "달콤한 허니머스타드 양념을 입힌 너겟", price: 6800, star: "4.8", review: 780, discount: 10, tag: "NEW", categories: "간식과일견과" },
{ title: "아몬드", description: "건강한 아몬드 200g", price: 5500, star: "4.7", review: 600, discount: 12, tag: "NEW", categories: "간식과일견과" },
{ title: "캐슈넛", description: "고소한 캐슈넛 200g", price: 6000, star: "4.9", review: 450, discount: 15, tag: "NEW", categories: "간식과일견과" },
{ title: "말린 망고", description: "달콤한 말린 망고 150g", price: 4200, star: "4.6", review: 320, discount: 8, tag: "NEW", categories: "간식과일견과" },
{ title: "사과칩", description: "바삭한 사과칩 100g", price: 3500, star: "4.8", review: 680, discount: 12, tag: "NEW", categories: "간식과일견과" },
{ title: "강황 가루", description: "건강에 좋은 강황 가루 150g", price: 4000, star: "4.9", review: 532, discount: 10, tag: "NEW", categories: "양념가루" },
{ title: "마늘 가루", description: "풍미를 더하는 마늘 가루 100g", price: 2500, star: "4.7", review: 850, discount: 5, tag: "NEW", categories: "양념가루" },
{ title: "고춧가루", description: "매운 맛을 더하는 고춧가루 200g", price: 3000, star: "4.8", review: 740, discount: 10, tag: "NEW", categories: "양념가루" },
{ title: "식물성 소시지", description: "100% 식물성으로 만든 소시지 6개입", price: 7200, star: "4.9", review: 430, discount: 12, tag: "NEW", categories: "고기대용" },
{ title: "콩고기", description: "고기 대체용 콩고기 500g", price: 6500, star: "4.8", review: 312, discount: 10, tag: "NEW", categories: "고기대용" },
{ title: "채소 고기", description: "양파와 버섯으로 만든 채소 고기 300g", price: 5400, star: "4.7", review: 210, discount: 15, tag: "NEW", categories: "고기대용" },
{ title: "양배추 볶음", description: "양배추와 버섯을 볶아 만든 간편 요리 300g", price: 2900, star: "4.6", review: 390, discount: 10, tag: "NEW", categories: "채식반찬" },
{ title: "콩나물 무침", description: "신선한 콩나물과 고추장을 넣어 만든 콩나물 무침", price: 2200, star: "4.8", review: 612, discount: 5, tag: "NEW", categories: "채식반찬" },
{ title: "된장찌개", description: "전통적인 된장찌개 500g", price: 4200, star: "4.9", review: 340, discount: 12, tag: "NEW", categories: "채식반찬" },
{ title: "비빔국수", description: "매콤한 양념과 함께 비빈 국수 1인분", price: 4500, star: "4.7", review: 432, discount: 8, tag: "NEW", categories: "채식반찬" },
{ title: "나물 반찬", description: "시금치, 고사리 등 다양한 나물 반찬 200g", price: 3500, star: "4.8", review: 345, discount: 10, tag: "NEW", categories: "채식반찬" },
{ title: "에그롤", description: "계란과 채소로 만든 에그롤 5개입", price: 5600, star: "4.7", review: 510, discount: 15, tag: "NEW", categories: "채식반찬" },
{ title: "호박전", description: "고소한 호박전을 4개입", price: 4000, star: "4.9", review: 720, discount: 12, tag: "NEW", categories: "채식반찬" },
{ title: "스파게티", description: "토마토 소스와 함께한 클래식 스파게티", price: 7200, star: "4.8", review: 890, discount: 5, tag: "NEW", categories: "간편식" },
{ title: "카레", description: "맛있는 카레와 밥이 함께 들어있는 간편식", price: 6500, star: "4.9", review: 760, discount: 10, tag: "NEW", categories: "간편식" },
{ title: "즉석 떡볶이", description: "매운 떡볶이 소스와 떡이 함께 들어있는 간편식", price: 3500, star: "4.7", review: 634, discount: 5, tag: "NEW", categories: "간편식" },
{ title: "김밥", description: "간편한 김밥 5개입", price: 4800, star: "4.8", review: 540, discount: 10, tag: "NEW", categories: "간편식" },
{ title: "치즈 떡볶이", description: "고소한 치즈 떡볶이 300g", price: 5600, star: "4.9", review: 430, discount: 12, tag: "NEW", categories: "간편식" },
{ title: "요거트", description: "상큼한 요거트 400g", price: 3900, star: "4.7", review: 620, discount: 10, tag: "NEW", categories: "간식과일견과" },
{ title: "건포도", description: "달콤한 건포도 150g", price: 2500, star: "4.6", review: 250, discount: 8, tag: "NEW", categories: "간식과일견과" },
{ title: "피스타치오", description: "고소한 피스타치오 200g", price: 7800, star: "4.9", review: 510, discount: 15, tag: "NEW", categories: "간식과일견과" },
{ title: "블루베리", description: "상큼한 블루베리 200g", price: 5500, star: "4.8", review: 430, discount: 12, tag: "NEW", categories: "간식과일견과" },
{ title: "바닐라 쿠키", description: "고소한 바닐라 쿠키 10개입", price: 4800, star: "4.7", review: 780, discount: 10, tag: "NEW", categories: "간식과일견과" }
)